<a href="https://colab.research.google.com/github/Jaeeun83/study/blob/main/tensor_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch as torch
import numpy as np

# 0차원 텐서 (scalar)

In [3]:
a = torch.tensor(1)

print(a)
print('차원 : ', torch.Tensor.dim(a))
print('사이즈 : ', torch.Tensor.size(a))

tensor(1)
차원 :  0
사이즈 :  torch.Size([])


# 1차원 텐서 (Vector)

In [5]:
b = torch.tensor([1,2,3])
print(b)
print('차원 : ', torch.Tensor.dim(b))
print('사이즈 : ', torch.Tensor.size(b))

tensor([1, 2, 3])
차원 :  1
사이즈 :  torch.Size([3])


In [6]:
b = torch.tensor([1])
print(b)
print('차원 : ', torch.Tensor.dim(b))
print('사이즈 : ', torch.Tensor.size(b))

tensor([1])
차원 :  1
사이즈 :  torch.Size([1])


# 2차원 텐서 (Matrix)

In [7]:
c = torch.tensor([[1,2,3],[4,5,6]])
print(c)
print('차원 : ', torch.Tensor.dim(c))
print('사이즈 : ', torch.Tensor.size(c))

tensor([[1, 2, 3],
        [4, 5, 6]])
차원 :  2
사이즈 :  torch.Size([2, 3])


In [8]:
c = torch.tensor([[1]])
print(c)
print('차원 : ', torch.Tensor.dim(c))
print('사이즈 : ', torch.Tensor.size(c))

tensor([[1]])
차원 :  2
사이즈 :  torch.Size([1, 1])


# 3차원 텐서


*   dim = 3
*   Size = (채널, 행, 열)



In [10]:
d = torch.tensor([[[1,2,3],[4,5,6]],[[3,2,5],[9,2,6]]])
print(d)
print('차원 : ', torch.Tensor.dim(d))
print('사이즈 : ', torch.Tensor.size(d))

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[3, 2, 5],
         [9, 2, 6]]])
차원 :  3
사이즈 :  torch.Size([2, 2, 3])


In [11]:
d = torch.tensor([[[1]]])
print(d)
print('차원 : ', torch.Tensor.dim(d))
print('사이즈 : ', torch.Tensor.size(d))

tensor([[[1]]])
차원 :  3
사이즈 :  torch.Size([1, 1, 1])


# 4차원 텐서

*   Size = (개수, 채널, 행, 열)



In [12]:
e = torch.tensor([[[[1,2,3],[4,5,6]],[[3,2,5],[9,2,6]]],
                  [[[2,9,7],[6,5,1]],[[2,9,8],[6,4,0]]],
                  [[[9,2,1],[6,4,1]],[[2,7,6],[5,8,6]]]])
print(e)
print('차원 : ', torch.Tensor.dim(e))
print('사이즈 : ', torch.Tensor.size(e))

tensor([[[[1, 2, 3],
          [4, 5, 6]],

         [[3, 2, 5],
          [9, 2, 6]]],


        [[[2, 9, 7],
          [6, 5, 1]],

         [[2, 9, 8],
          [6, 4, 0]]],


        [[[9, 2, 1],
          [6, 4, 1]],

         [[2, 7, 6],
          [5, 8, 6]]]])
차원 :  4
사이즈 :  torch.Size([3, 2, 2, 3])


In [13]:
e = torch.tensor([[[[1]]]])
print(e)
print('차원 : ', torch.Tensor.dim(e))
print('사이즈 : ', torch.Tensor.size(e))

tensor([[[[1]]]])
차원 :  4
사이즈 :  torch.Size([1, 1, 1, 1])
